# Generated by Django 3.2.5 on 2021-07-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='date',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='class',
            name='time',
            field=models.TextField(max_length=50),
        ),
    ]
