# Generated by Django 3.2.5 on 2021-07-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_auto_20210717_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='time',
        ),
        migrations.AddField(
            model_name='class',
            name='time_end',
            field=models.TextField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='time_start',
            field=models.TextField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
